### ISSUE TITLE
Problem with mqtt

### ISSUE THREAD

**Issue by BoNiFachio** [deiger/AirCon#129]
Hello.
When i conect everything is ok, the devices are discovered but it seems to be a problem with mqtt.
this the messge.
 File "/usr/local/lib/python3.7/site-packages/aiohttp-3.7.4-py3.7-linux-aarch64.egg/aiohttp/web_runner.py", line 128, in start
    reuse_port=self._reuse_port,
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 1389, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 1883): address already in use

any one knows what is the problem.

Best regards.

**Comment by hzpz** [comment]
Is this a message from AirCon? It seems more like a message from your MQTT broker.

**Comment by deiger** [comment]
What is the config you run it with? Did you accidentally use 1883 as `--port`?

**Comment by BoNiFachio** [comment]
I use HA instaled in promox machine. 
this is my config in the Aircon addon.
log_level: INFO
mqtt_host: 192.1xx.x.xxx
mqtt_user: xxxcccxxxccc
mqtt_pass: zxczxc
port: 1883
app:
  - username: rxdfcgv@xxxxx
    password: 123qweasd
    code: hisense-eu

**Comment by hzpz** [comment]
There you go, `port: 1883` is the problem. This is the port that AirCon uses for itself, **not** the port for the connection to the MQTT broker. If you want to configure the latter, you might try `mqtt_port: 1883` instead. I'm not sure if the Home Assistant Add-on supports this though, and since 1883 is the default, you probably won't have to configure it at all. Just delete the line `port: 1883` and you should be good to go.

**Comment by BoNiFachio** [comment]
god bless you.
Well done.
Now its all ok :)
Many thanks
