### ISSUE TITLE
Command issue from 2023.12

### ISSUE THREAD

**Issue by kevtuning** [deiger/AirCon#267]
Hi guys,

Have you issues from 2023.12 update ?

This morning, my house was cold because the Aircon didn't fired up.

I restarted the add-on and it worked again.

Later in the morning same thing... need to restart the add-on to adjust the temperature.

I have restarted completely the system (HA + OS) and sending commands was working but I wasn't receiving mqtt messages in return during a while and after it worked fine till next time.

SO as summary, almost each time a want to send commands to the Aircon, I need restart the add-on first.

Anyone faced the same issue ?

**Comment by kevtuning** [comment]
I've not precised.. but I see no error in the logs (in debug) ... I just don't seen mqtt messages as expected...

**Comment by ceemjay** [comment]
I am not sure if I have the same problem as you or not but pretty much daily I have to restart the Add-on. It have set 
"Watchdog=This will start the add-on if it crashes" so maybe it's hanging rather than crashing?

On my card each of the heaters is greyed out and marked as unavailable until the restart.

I am a relative newbie and not really up to speed with logs/debugging. Happy to provide any further info if given some guidance,

**Comment by kevtuning** [comment]
Okay...

It seems like that I've not anymore the issue... 

It may be due to the wifi interface of the Aircon... that I have rebooted...
